name: Gradle Publish

on:
  release:
      types: [created]
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Gradle Build
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build

      - name: Gradle Publish
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: publish -Dorg.gradle.project.version=${{ github.event.release.tag_name }}
        env:
          USERNAME: ${{ github.repository_owner }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload a Build Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
